title: Leonardo Silva - Portfólio e Blog
description: Portfólio e blog de um Analista de Planejamento e Operações
baseurl: ""
url: "https://seu-site.pages.dev"
theme: null
plugins:
  - jekyll-feed
collections:
  projects:
    output: true
