title: Leonardo Silva - Blog
description: Blog de um Analista de Planejamento e Operações
baseurl: ""
url: "https://blog-oleonardof.pages.dev
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap