# Nome do seu fluxo de trabalho
name: Build and Deploy Jekyll Site

# Define quando a Action deve rodar
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # ADICIONADO: Concede permissões para a Action escrever no repositório.
    # Isso é necessário para que ela consiga criar e atualizar a branch 'gh-pages'.
    permissions:
      contents: write

    steps:
      # Passo 1: Clona o seu repositório
      - name: Checkout
        uses: actions/checkout@v4

      # Passo 2: Configura o ambiente Ruby e o Bundler
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      # Passo 3: Constrói o site Jekyll
      - name: Build Jekyll site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      # Passo 4: Publica o site no GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site